// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnA7u3V0kKwX5duyb87GmkHIISCOdQ42Y',
    appId: '1:127466433935:web:50e7b57317d590c5f82ffa',
    messagingSenderId: '127466433935',
    projectId: 'green-transit',
    authDomain: 'green-transit.firebaseapp.com',
    storageBucket: 'green-transit.appspot.com',
    measurementId: 'G-43P73EE5W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA91qdAWGit70t9iUPtGbuLsO75Jw-O-go',
    appId: '1:127466433935:android:a30dfb05e3b9da07f82ffa',
    messagingSenderId: '127466433935',
    projectId: 'green-transit',
    storageBucket: 'green-transit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYW5L1zFhDgBUfj2PfGAjtNuRqBCbgSnM',
    appId: '1:127466433935:ios:97385aeb2d294987f82ffa',
    messagingSenderId: '127466433935',
    projectId: 'green-transit',
    storageBucket: 'green-transit.appspot.com',
    iosBundleId: 'com.example.greenware',
  );
}
